title: "React-classroom, Crea Apps con React en cualquier plataforma."
description: "Aprende React, Ionic, Firebase, Nativescript y desarrolla increibles apps para Android y IOS."
keywords: "react,html5,javascript,mobile,ionic,hybrid,phonegap,cordova,native,ios,android,curso de react, aprender react"

baseurl: ""
urlblog: '/blog'
cover: "/images/cover.jpg"
path: 'https://www.react-classroom.com/'

pwa_enabled: 0
ads_enabled: 0
push_notifications: 0
google_optimize: 0
google_cse: 0
google_tagmanager: 0
hello_bar_enabled: 0
disqus_comments: 0

timezone: "America/Bogota"

markdown: kramdown
permalink: blog/:categories/:title/
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
sass:
    style: compressed
excerpt_separator: <!--summary-->
exclude: [CNAME,'*.sh','*.json','README.md']